import java.sql.*; 
import Project.ConnectionProvider;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mohammad Ali
 */
public class deleteQuestion extends javax.swing.JFrame {

    /**
     * Creates new form deleteQuestion
     */
    public deleteQuestion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        closeBtn = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        answerTxt = new javax.swing.JTextField();
        option4Txt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        option3Txt = new javax.swing.JTextField();
        option2Txt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        option1Txt = new javax.swing.JTextField();
        questTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        dltBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(150, 183));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete Question.png"))); // NOI18N
        jLabel1.setText("Delete Question");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close (1).png"))); // NOI18N
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
        });
        getContentPane().add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, -1, 50));

        jLabel10.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Answer :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 106, 31));

        answerTxt.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        answerTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerTxtActionPerformed(evt);
            }
        });
        getContentPane().add(answerTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 424, 699, 31));

        option4Txt.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        getContentPane().add(option4Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 372, 699, 35));

        jLabel9.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Option 4 :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 106, 35));

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Option 3 :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 106, 29));

        option3Txt.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        getContentPane().add(option3Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 322, 699, 29));

        option2Txt.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        option2Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option2TxtActionPerformed(evt);
            }
        });
        getContentPane().add(option2Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 272, 699, 29));

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Option 2 :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 106, 29));

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Option 1 :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 106, 32));

        option1Txt.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        getContentPane().add(option1Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 222, 699, 32));

        questTxt.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        questTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questTxtActionPerformed(evt);
            }
        });
        getContentPane().add(questTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 166, 699, 34));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Question : ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, 34));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Question Id: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        idTxt.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        getContentPane().add(idTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 118, 153, 30));

        searchBtn.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, -1, 30));

        dltBtn.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        dltBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        dltBtn.setText("Delete");
        dltBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dltBtnActionPerformed(evt);
            }
        });
        getContentPane().add(dltBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, 119, 37));

        clearBtn.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        clearBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clear.png"))); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        getContentPane().add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 470, 110, 37));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1070, 10));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seige.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        // TODO add your handling code here:
        adminHomepage.open=0;
        setVisible(false);
    }//GEN-LAST:event_closeBtnMouseClicked

    private void answerTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answerTxtActionPerformed

    private void option2TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option2TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_option2TxtActionPerformed

    private void questTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_questTxtActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        String id=idTxt.getText();
        try
        {
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();//to retreive data from database
            ResultSet rs=st.executeQuery("select * from question where id='"+id+"'");
            if(rs.first())
            {
                questTxt.setText(rs.getString(2));
                option1Txt.setText(rs.getString(3));
                option2Txt.setText(rs.getString(4));
                option3Txt.setText(rs.getString(5));
                option4Txt.setText(rs.getString(6));
                answerTxt.setText(rs.getString(7));
                idTxt.setEditable(false);
            }
            //if id doesn't exists
            else
            {
                JFrame jf=new JFrame();
                jf.setAlwaysOnTop(true);
                JOptionPane.showMessageDialog(jf,"Question id doesn't exists!");
            }
        }
        catch(Exception e)
        {
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,e);
        }
        
    }//GEN-LAST:event_searchBtnActionPerformed

    private void dltBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dltBtnActionPerformed
        // TODO add your handling code here:
        String id=idTxt.getText();
        try
        {
            Connection con=ConnectionProvider.getCon();
            PreparedStatement ps=con.prepareStatement("delete from question where id=?");
            ps.setString(1,id);
            ps.executeUpdate();
            
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,"Successfully deleted");
            setVisible(false);
            new deleteQuestion().setVisible(true);
           
        }
        catch(Exception e)
        {
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,e);
        }
    }//GEN-LAST:event_dltBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        idTxt.setText("");
        questTxt.setText("");
        option1Txt.setText("");
        option2Txt.setText("");
        option3Txt.setText("");
        option4Txt.setText("");
        answerTxt.setText("");
        idTxt.setEditable(true);
    }//GEN-LAST:event_clearBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deleteQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deleteQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deleteQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deleteQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deleteQuestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answerTxt;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel closeBtn;
    private javax.swing.JButton dltBtn;
    private javax.swing.JTextField idTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField option1Txt;
    private javax.swing.JTextField option2Txt;
    private javax.swing.JTextField option3Txt;
    private javax.swing.JTextField option4Txt;
    private javax.swing.JTextField questTxt;
    private javax.swing.JButton searchBtn;
    // End of variables declaration//GEN-END:variables
}
