

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mohammad Ali
 */
public class index extends javax.swing.JFrame {

    /**
     * Creates new form index
     */
    public index() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exitBtn = new javax.swing.JLabel();
        studBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        teachBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitBtn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close_button.png"))); // NOI18N
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
        });
        getContentPane().add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 10, 50, 50));

        studBtn.setBackground(new java.awt.Color(204, 0, 255));
        studBtn.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        studBtn.setText("As a Student");
        studBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                studBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                studBtnMouseExited(evt);
            }
        });
        studBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studBtnActionPerformed(evt);
            }
        });
        getContentPane().add(studBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 490, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teacher (2).png"))); // NOI18N
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graduating-student.png"))); // NOI18N
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 220, -1, -1));

        teachBtn.setBackground(new java.awt.Color(204, 0, 255));
        teachBtn.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        teachBtn.setText("As a Teacher");
        teachBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teachBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                teachBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                teachBtnMouseExited(evt);
            }
        });
        teachBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teachBtnActionPerformed(evt);
            }
        });
        getContentPane().add(teachBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 490, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/49-497241_study-hd-wallpaper-for-laptop.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null,"Do you really want to exit?","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_exitBtnMouseClicked

    
   
    
    public void setColor(JButton s)
    {
        s.setBackground(new Color(204,0,255));
    }
    public void resetColor(JButton s)
    {
        s.setBackground(new Color(204,102,255));
    }
    private void studBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studBtnMouseEntered
        // TODO add your handling code here:
        setColor(studBtn);
    }//GEN-LAST:event_studBtnMouseEntered

    private void studBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studBtnMouseExited
        // TODO add your handling code here:
        resetColor(studBtn);
    }//GEN-LAST:event_studBtnMouseExited

    private void studBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studBtnMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new RegisterForm().setVisible(true);
    }//GEN-LAST:event_studBtnMouseClicked

    private void teachBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teachBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_teachBtnMouseClicked

    
    private void teachBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teachBtnMouseEntered
        // TODO add your handling code here:
        setColor(teachBtn);
    }//GEN-LAST:event_teachBtnMouseEntered

    private void teachBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teachBtnMouseExited
        // TODO add your handling code here:
        resetColor(teachBtn);
    }//GEN-LAST:event_teachBtnMouseExited

    private void teachBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teachBtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new AdminLogin().setVisible(true);
    }//GEN-LAST:event_teachBtnActionPerformed

    private void studBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studBtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new RegisterForm().setVisible(true);
    }//GEN-LAST:event_studBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton studBtn;
    private javax.swing.JButton teachBtn;
    // End of variables declaration//GEN-END:variables
}
