import java.sql.*;
import Project.ConnectionProvider;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mohammad Ali
 */
public class ModifyQuestion extends javax.swing.JFrame {

    /**
     * Creates new form updateQuestion
     */
    public ModifyQuestion() {
        initComponents();
    }
    
    
    public void clearFields()
    {
        idTxt.setText("");
        questTxt.setText("");
        option1Txt.setText("");
        option2Txt.setText("");
        option3Txt.setText("");
        option4Txt.setText("");
        answerTxt.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        questTxt = new javax.swing.JTextField();
        option1Txt = new javax.swing.JTextField();
        option2Txt = new javax.swing.JTextField();
        option3Txt = new javax.swing.JTextField();
        option4Txt = new javax.swing.JTextField();
        answerTxt = new javax.swing.JTextField();
        updtBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JLabel();
        dltBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(150, 183));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Update Question.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel2.setText("Update & Delete Question");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 19, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 77, 1066, 10));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Question Id: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Question : ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, 34));

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Option 1 :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 106, 32));

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Option 2 :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 106, 29));

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Option 3 :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 106, 29));

        jLabel9.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Option 4 :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 106, 35));

        jLabel10.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Answer :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 106, 31));

        idTxt.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        getContentPane().add(idTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 118, 153, 30));

        searchBtn.setBackground(new java.awt.Color(102, 153, 0));
        searchBtn.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, -1, 30));

        questTxt.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        questTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questTxtActionPerformed(evt);
            }
        });
        getContentPane().add(questTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 166, 699, 34));

        option1Txt.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        getContentPane().add(option1Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 222, 699, 32));

        option2Txt.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        option2Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option2TxtActionPerformed(evt);
            }
        });
        getContentPane().add(option2Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 272, 699, 29));

        option3Txt.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        getContentPane().add(option3Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 322, 699, 29));

        option4Txt.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        getContentPane().add(option4Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 372, 699, 35));

        answerTxt.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        answerTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerTxtActionPerformed(evt);
            }
        });
        getContentPane().add(answerTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 424, 699, 31));

        updtBtn.setBackground(new java.awt.Color(102, 153, 0));
        updtBtn.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        updtBtn.setForeground(new java.awt.Color(255, 255, 255));
        updtBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        updtBtn.setText("Update");
        updtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updtBtnActionPerformed(evt);
            }
        });
        getContentPane().add(updtBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, 170, 37));

        clearBtn.setBackground(new java.awt.Color(0, 0, 255));
        clearBtn.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        clearBtn.setForeground(new java.awt.Color(255, 255, 255));
        clearBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clear.png"))); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        getContentPane().add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 470, 170, 37));

        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close_button.png"))); // NOI18N
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
        });
        getContentPane().add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 10, 50, 50));

        dltBtn.setBackground(new java.awt.Color(153, 51, 255));
        dltBtn.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        dltBtn.setForeground(new java.awt.Color(255, 255, 255));
        dltBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        dltBtn.setText("Delete");
        dltBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dltBtnActionPerformed(evt);
            }
        });
        getContentPane().add(dltBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 470, 160, 37));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seige.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void questTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_questTxtActionPerformed

    private void option2TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option2TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_option2TxtActionPerformed

    private void answerTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answerTxtActionPerformed

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        // TODO add your handling code here:
        adminHomepage.open=0;
        setVisible(false);
    }//GEN-LAST:event_closeBtnMouseClicked

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        String id=idTxt.getText();
        try
        {
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();//to retreive data from database
            ResultSet rs=st.executeQuery("select * from question where id='"+id+"'");
            if(rs.first())
            {
                questTxt.setText(rs.getString(2));
                option1Txt.setText(rs.getString(3));
                option2Txt.setText(rs.getString(4));
                option3Txt.setText(rs.getString(5));
                option4Txt.setText(rs.getString(6));
                answerTxt.setText(rs.getString(7));
                idTxt.setEditable(false);
            }
            //if id doesn't exists
            else
            {
                //JFrame jf=new JFrame();
                //jf.setAlwaysOnTop(true);
                JOptionPane.showMessageDialog(this,"Question id doesn't exists!");
               
            }
        }
        catch(Exception e)
        {
            //JFrame jf=new JFrame();
            //jf.setAlwaysOnTop(true);
            //JOptionPane.showMessageDialog(jf,e);
            Logger.getLogger(ModifyQuestion.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void updtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updtBtnActionPerformed
        // TODO add your handling code here:
        String id=idTxt.getText();
        String name=questTxt.getText();
        String opt1=option1Txt.getText();
        String opt2=option2Txt.getText();
        String opt3=option3Txt.getText();
        String opt4=option4Txt.getText();
        String answer=answerTxt.getText();
        boolean flag=true;
        String message;
        
         try{
            
            Connection con=ConnectionProvider.getCon();
            PreparedStatement ps=con.prepareStatement("update question set name=?,opt1=?,opt2=?,opt3=?,opt4=?,answer=? where id=?");
            
            ps.setString(1, name);
            ps.setString(2, opt1);
            ps.setString(3, opt2);
            ps.setString(4, opt3);
            ps.setString(5, opt4);
            ps.setString(6, answer);
            ps.setString(7, id);
            ps.executeUpdate();
            
            flag=true;
            message="Question updated successfuly";
            
        }
        catch(Exception e)
        {
            System.out.println("there is a problem"+" "+e);
            flag=false;
            message="Opps! "+e;
        }
         
        if(flag){
            JOptionPane.showMessageDialog(this, message);
        }
        else{
            JOptionPane.showMessageDialog(this, message);
        }
        
        clearFields();
         
    }//GEN-LAST:event_updtBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        idTxt.setText("");
        questTxt.setText("");
        option1Txt.setText("");
        option2Txt.setText("");
        option3Txt.setText("");
        option4Txt.setText("");
        answerTxt.setText("");
        idTxt.setEditable(true);
    }//GEN-LAST:event_clearBtnActionPerformed

    private void dltBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dltBtnActionPerformed
        // TODO add your handling code here:
        
        String id=idTxt.getText();
        boolean flag=true;
        String message;
        System.out.println(id);
        try
        {
            Connection con=ConnectionProvider.getCon();
            PreparedStatement ps=con.prepareStatement("delete from question where id=?");
            ps.setString(1,id);
            ps.executeUpdate();
            System.out.println("deleted successfuly");
            flag=true;
            message="Question deleted successfuly";
            //setVisible(false);
            //new ModifyQuestion().setVisible(true);
            
        }
        catch(Exception e)
        {
            System.out.println("there is a problem"+" "+e);
            flag=false;
            message="Opps! "+e;
        }
        if(flag){
            JOptionPane.showMessageDialog(this, message);
        }
        else{
            JOptionPane.showMessageDialog(this, message);
        }
        
        clearFields();
        
    }//GEN-LAST:event_dltBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifyQuestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answerTxt;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel closeBtn;
    private javax.swing.JButton dltBtn;
    private javax.swing.JTextField idTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField option1Txt;
    private javax.swing.JTextField option2Txt;
    private javax.swing.JTextField option3Txt;
    private javax.swing.JTextField option4Txt;
    private javax.swing.JTextField questTxt;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton updtBtn;
    // End of variables declaration//GEN-END:variables
}
