import java.sql.*;
import Project.ConnectionProvider;
import java.awt.Font;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mohammad Ali
 */
public class ResultPage extends javax.swing.JFrame {

    /**
     * Creates new form ResultPage
     */
    public ResultPage() {
        initComponents();
        
        
        loadTableData();
        //resultTable.setAutoResizeMode(resultTable.AUTO_RESIZE_OFF);
        JTableHeader tableHeader = resultTable.getTableHeader();
        Font headerFont = new Font("Cambria", Font.BOLD, 16);
        tableHeader.setFont(headerFont);
    }
    
    
    private void loadTableData(){
        
            try {
                
                Connection con= ConnectionProvider.getCon();
                Statement st=con.createStatement();
                ResultSet rs=st.executeQuery("select * from student");
                DefaultTableModel model = (DefaultTableModel)resultTable.getModel();
                model.setRowCount(0);
                
                try {
                    
                    while(rs.next()){
                        Vector colData = new Vector();
                        colData.add(rs.getString("id"));
                        colData.add(rs.getString("name"));
                        colData.add(rs.getString("gender"));
                        colData.add(rs.getString("mobile_no"));
                        colData.add(rs.getString("email"));
                        colData.add(rs.getString("marks"));
                        
                        Connection con2= ConnectionProvider.getCon();
                        Statement st2=con2.createStatement();
                        ResultSet rs2=st2.executeQuery("select opinion from review where st_id='"+rs.getString("id")+"'");
                        if(rs2.next()){
                            colData.add(rs2.getString("opinion"));
                        }
                        
                        //colData.add(rs.getString("answer"));
                        
                        model.addRow(colData);
                    }
                    
                } catch (SQLException ex) {
                    Logger.getLogger(ResultPage.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(ResultPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        searchTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();
        closeBtn = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(150, 183));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test.png"))); // NOI18N
        jLabel1.setText("Results Of The Students");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        searchTxt.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        searchTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTxtActionPerformed(evt);
            }
        });
        searchTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTxtKeyReleased(evt);
            }
        });
        getContentPane().add(searchTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 200, 30));

        resultTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        resultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Gender", "Mobile No.", "Email", "Marks", "Review Given"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(resultTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 970, 350));

        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close_button.png"))); // NOI18N
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
        });
        getContentPane().add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 10, 50, 50));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1070, 10));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel4.setText("Filter Students By Marks :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seige.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTxtActionPerformed

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        // TODO add your handling code here:
        adminHomepage.open=0;
        setVisible(false);
    }//GEN-LAST:event_closeBtnMouseClicked

    private void searchTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTxtKeyReleased
        // TODO add your handling code here:
        int marks;
        if(searchTxt.getText().equals(""))
        {
            marks=0;
        }
        else
        
            marks=Integer.parseInt(searchTxt.getText());
        
            
            try
        {
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();//to retreive data from database
            ResultSet rs=st.executeQuery("select * from student where marks >="+marks+"");
            DefaultTableModel model = (DefaultTableModel)resultTable.getModel();
            model.setRowCount(0);
            
            try {
                    
                    while(rs.next()){
                        Vector colData = new Vector();
                        colData.add(rs.getString("id"));
                        colData.add(rs.getString("name"));
                        colData.add(rs.getString("gender"));
                        colData.add(rs.getString("mobile_no"));
                        colData.add(rs.getString("email"));
                        colData.add(rs.getString("marks"));
                        
                        Connection con2= ConnectionProvider.getCon();
                        Statement st2=con2.createStatement();
                        ResultSet rs2=st2.executeQuery("select opinion from review where st_id='"+rs.getString("id")+"'");
                        if(rs2.next()){
                            colData.add(rs2.getString("opinion"));
                        }
                        
                        //colData.add(rs.getString("answer"));
                        
                        model.addRow(colData);
                    }
                    
                } catch (SQLException ex) {
                    Logger.getLogger(ResultPage.class.getName()).log(Level.SEVERE, null, ex);
                }
           
        }
        catch(Exception e)
        {
            Logger.getLogger(ResultPage.class.getName()).log(Level.SEVERE, null, e);
        
        }
        
        
    }//GEN-LAST:event_searchTxtKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResultPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel closeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable resultTable;
    private javax.swing.JTextField searchTxt;
    // End of variables declaration//GEN-END:variables
}
